spring:
  datasource:
    url: jdbc:mysql://192.168.88.128:3306/springboot
    username: root
    password: 52Perseverance_
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      aop-patterns: com.example.admin.*
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        reset-enable: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true

        wall:
          enabled: true
          config:
            drop-table-allow: false
  boot:
    admin:
      client:
        url: http://localhost:8888

#配置mybatis的全局配置文件和mapper接口的文件的位置即可。
#如果同时写config-location和configuration就会报错
#报java.lang.IllegalStateException: Property 'configuration' and 'configLocation' can not specified with together
#解决办法，全局配置文件位置去掉，所有全局配置写在configuration下
mybatis:
 # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: #指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true



management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

info:
  env:
    enabled: true
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@

